---
title: "Woodruff - Thesis - R code"
author: "Chelsea Woodruff"
date: "3/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
myData0305 <- read.csv("~/Desktop/Thesis & Related Items/R Stuff/ThesisData03122019.csv")

myData <- read.csv(paste("~/Desktop/Thesis & Related Items/R Stuff/ThesisData03122019.csv"), skip=2)

names(myData) <- c("StartDate", "EndDate", "IPStatus", "Progress", "DurationSec", "Finished", "RecDate", "ResponseID", "DistChannel", "UserLang", "WouldBuy", "Q1", "Q2", "Q3", "Q4", "Q5", "Q6", "Q7", "Q8", "Q9", "Q10", "Q11", "Q12", "Q13", "Q14", "Q15", "Q16", "Q17", "Q18", "Q19", "Q20", "Q21", "Q22", "Q23", "Q24", "Q25", "PriorKnowledge", "Gender", "YearBorn", "ZipCode", "Income", "Race", "Education", "Citizen", "Q34", "Q35", "Q36")
```

```{r}

myData$Education <- ifelse(myData$Education =="Less than high school diploma", 1,
  ifelse(myData$Education =="High school degree or equivalent (e.g. GED)", 2,
  ifelse(myData$Education =="Some college, no degree", 3,
  ifelse(myData$Education =="Associate degree (e.g. AA, AS)", 4,
  ifelse(myData$Education =="Bachelor’s degree (e.g. BA, BS)", 5,
  ifelse(myData$Education =="Master’s degree (e.g. MA, MS, MEd)", 6,
  ifelse(myData$Education =="Professional degree (e.g. MD, DDS, DVM)", 7,
  ifelse(myData$Education =="Doctorate (e.g. PhD, EdD)", 8, 'FAIL'
))))))))
```
```{r}
myData$Income <- ifelse(myData$Income =="Less than $10,000", 1,
  ifelse(myData$Income =="$10,000 - $24,999", 2, 
  ifelse(myData$Income =="$25,000 - $49,999", 3, 
  ifelse(myData$Income =="$50,000 - $74,999", 4,
  ifelse(myData$Income =="$75,000 - $99,999", 5,
  ifelse(myData$Income =="$100,000 - $124,999", 6,
  ifelse(myData$Income =="$125,000 - $149,999", 7, 
  ifelse(myData$Income =="$150,000 - $174,999", 8,
  ifelse(myData$Income =="$175,000 – $199,999", 9,
  ifelse(myData$Income =="$200,000 and higher", 10, 'FAIL'
  ))))))))))
```
```{r}
myData$Race <- ifelse(myData$Race == 'White or Caucasian', 1, 0)
```


```{r}
myData$Q5<-as.numeric(myData$Q5)
```

```{r}
q2price = gsub("$", "", as.character(myData$Q2), fixed=T)
tmp = unlist(lapply(strsplit(q2price, ","), function(x) max(as.numeric(x))))
tmp = ifelse(is.infinite(tmp), NA, tmp)
```